# Generated by Django 4.0 on 2022-12-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagen', verbose_name='imagen'),
        ),
    ]
