# Generated by Django 4.0 on 2023-02-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0004_product_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descripcion',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='descripcion'),
        ),
    ]
